spring:
  application:
    name: SEBM
#  profiles:
#    active: ${SPRING_PROFILES_ACTIVE:local}

  datasource:
    url: jdbc:mysql://trolley.proxy.rlwy.net:29578/railway?useSSL=false&serverTimezone=UTC
    username: root
    password: RxAHOOQJjTtBblTpadijgyIWmArpvibI
    driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    type: redis
  data:
    redis:
      host: caboose.proxy.rlwy.net
      port: 13462
      username: default
      password: ekseulHMMJJMoAFIOLchTXsnRDbpMHff

  # Mail configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:sebm.notifications@gmail.com}
    password: ${MAIL_PASSWORD:mysr cwqu lybt mdmv}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com

  # RabbitMQ configuration for Railway deployment
  rabbitmq:
    host: hopper.proxy.rlwy.net
    port: 50343
    username: test
    password: test
    virtual-host: /
    ssl:
       enabled: false
    connection-timeout: 15000
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000
          max-interval: 10000
          multiplier: 2
server:
  port: 29578
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'api'
      paths-to-match: /**
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

aliyun:
  oss:
    endpoint: oss-ap-southeast-1.aliyuncs.com
    accessKeyId: ${OSS_ACCESS_KEY_ID}
    accessKeySecret: ${OSS_ACCESS_KEY_SECRET}
    bucketName: sebm

