spring:
  application:
    name: SEBM
#  profiles:
#    active: ${SPRING_PROFILES_ACTIVE:local}

  datasource:
    url: jdbc:mysql://trolley.proxy.rlwy.net:29578/railway?useSSL=false&serverTimezone=UTC
    username: root
    password: RxAHOOQJjTtBblTpadijgyIWmArpvibI
    driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    type: redis
  data:
    redis:
      host: caboose.proxy.rlwy.net
      port: 13462
      username: default
      password: ekseulHMMJJMoAFIOLchTXsnRDbpMHff

  # Mail configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:sebm.notification@gmail.com}
    password: ${MAIL_PASSWORD:vuxi nfwf jpmc koow}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
server:
  port: 29578
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'api'
      paths-to-match: /**
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

# RocketMQ configuration
rocketmq:
  name-server: ${ROCKETMQ_NAME_SERVER:localhost:9876}
  producer:
    group: ${ROCKETMQ_PRODUCER_GROUP:sebm-producer-group}
    send-message-timeout: 3000
    retry-times-when-send-failed: 2
    retry-times-when-send-async-failed: 2
    max-message-size: 4194304
    compress-message-body-threshold: 4096
  consumer:
    group: ${ROCKETMQ_CONSUMER_GROUP:sebm-consumer-group}

tencent:
  cos:
    secretId: ${TENCENT_SECRET_ID:default}
    secretKey: ${TENCENT_SECRET_KEY:default}
    region: ${TENCENT_REGION:default}
    bucketName: sebm-1354340785
    durationSeconds: 900
